# Basic Information
title: "Yichen Xie"
description: |
  Master student in Robotics 
  <h3>📞 Contact</h3>
  <p>Email: <a href="mailto:yxie78@jhu.edu">yxie78@jhu.edu</a></p>
  <p>GitHub: <a href="https://github.com/Fireleaf16">Fireleaf16</a></p>
  <p>LinkedIn: <a href="https://linkedin.com/in/yichen-xie-137333291">yichenxie</a></p>
author: "Yichen Xie"
email: "yxie78@jhu.edu"

# Theme
theme: jekyll-theme-minimal
logo: "/images/profile.jpg"

# Website URL
baseurl: ""
url: "https://Fireleaf16.github.io"

# Navigation
navbar-links:
  Home: "index.md"
  Publications: "publications.md"
  Research: "research.md"

# Markdown 
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..3



