# Basic Information
title: "Yichen Xie"
description: "Master student in Robotics"
author: "Yichen Xie"
email: "yxie78@jhu.edu"

# Theme
theme: jekyll-theme-minimal

# Website URL
baseurl: ""
url: "https://Fireleaf16.github.io"

# Navigation
navbar-links:
  Home: "index.md"
  Publications: "publications.md"
  Research: "research.md"
  Contact: "contact.md"

# Markdown 
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..3



