# Basic Information
title: "Yichen Xie"
# Yichen Xie
<img src="images/profile.jpg" width="150" align="left" style="border-radius: 50%; margin-right: 15px;">

**Master student in Robotics**  
[View My GitHub Profile](https://github.com/Fireleaf16)

author: "Yichen Xie"
email: "yxie78@jhu.edu"

# Theme
theme: jekyll-theme-minimal

# Website URL
baseurl: ""
url: "https://Fireleaf16.github.io"

# Nevigation
navbar-links:
  Home: "index.md"
  Publications: "publications.md"
  Research: "research.md"
  Contact: "contact.md"

# Markdown 
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..3


